{% set name = "foundry-dev-tools-transforms" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/foundry_dev_tools_transforms-{{ version }}.tar.gz
  sha256: 94d1fd0062b9b62a602a61788aef34e2786fda83df2f5df414106914ee6126e7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - pdm-backend
    - pip
  run:
    - python >=3.10
    - foundry-dev-tools
    - typing_extensions
    - pyspark >=3.0.0
    - numpy <2
    - fs

test:
  imports:
    - transforms
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/emdgroup/foundry-dev-tools
  summary: Seamlessly run your Palantir Foundry Repository transforms code on your local machine.
  dev_url: https://github.com/emdgroup/foundry-dev-tools
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jonas-w
    - nicornk
